name: Website Monitor

on:
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
      - name: Repository klonen
        uses: actions/checkout@v2

      - name: Setze Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Ersetze '3.x' durch die gewünschte Version

      - name: Installiere Abhängigkeiten
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Führe das Skript aus
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python check_updates.py
